apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaurgak-mu-aks-api-km
  namespace: kaurgak
  labels:
    app: kaurgak-mu-aks-api-km
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaurgak-mu-aks-api-km
  template:
    metadata:
      labels:
        app: kaurgak-mu-aks-api-km
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      containers:
        - name: kaurgak-mu-aks-api-km
          image: {{ .Values.imageRegistry }}/kaurgak-mu-aks-api-km:{{ .Values.apiDockerTag }}
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
          ports:
            - containerPort: 4000