apiVersion: v1
kind: Service
metadata:
  name: kaurgak-mu-aks-api
  namespace: kaurgak
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  type: LoadBalancer
  selector:
    app: kaurgak-mu-aks-api
  ports:
    - port: 80
      targetPort: 3001